### PR TITLE
#INF-0001: Added One to many relation in person and address.

### PR DESCRIPTION
**Pull request by devbinod**

### CODE REVIEW

**Review by developer-harisubedi — CHANGES_REQUESTED** [review]
Seems good!

**Review by arjunghimire5 — CHANGES_REQUESTED** [review]
Please format change.

**Review by developer-harisubedi — APPROVED** [review]
Code approved!

**Review by arjunghimire5 — APPROVED** [review]
Wow!! Kya semicolumn he.

**Comment by devbinod** [comment]
#merger inoto develop

**Pull request merged**
